// const BASE_URL = "http://localhost:8000/api/";
const BASE_URL = "https://legal-vise-server.vercel.app/api/";

// AUTH ENDPOINTS
export const endpoints = {
  LOGIN_API: BASE_URL + "customer/login",
  ADMIN_LOGIN_API: BASE_URL + "admin/login",
  PROFILE_DETAILS: BASE_URL + "customer/getDetails",
  SPLOGIN_API: BASE_URL + "serviceProvider/login",
  SPPROFILE_DETAILS: BASE_URL + "serviceProvider/getDetails",
  GETALLJOBS: BASE_URL + "jobs/getall",
  CREATE_JOB: BASE_URL + "jobs/create",
  CUSTOMER_JOBS: BASE_URL + "jobs/find/",
  APPLYJOB: BASE_URL + "jobs/interested",
  GETONEJOB: BASE_URL + "jobs/getOne",
  CHECKINTERESTED: BASE_URL + "jobs/checkInterested",
  CHANGE_JOB_STATUS: BASE_URL + "jobs/updateJobStatus/",
  GETALLAPPLIEDJOBS: BASE_URL + "serviceProvider/getAllServiceProviderJobs",
  GETALLSELECTEDJOBS: BASE_URL + "serviceProvider/getAllSelectedJobs",
  GETCLIENTDETAILS: BASE_URL + "customer/getDetails",
  ADDWISHLIST: BASE_URL + "serviceProvider/addToWishlist",
  REMOVEWISHLIST: BASE_URL + "serviceProvider/removeFromWishlist",
  GETWISHLIST: BASE_URL + "serviceProvider/getWishlistJobs",
  GETSIMILARCLIENTS: BASE_URL + "customer/getSimilarUsers",
  GETSIMILARSP: BASE_URL + "serviceProvider/getSimilarServiceProviders",
  GETSPDETAILSBYID: BASE_URL + "serviceProvider/getDetails/",
  GET_INTERESTED_DETAILS: BASE_URL + "customer/getInterestedDetails",
  ADD_UNLOCKED: BASE_URL + "customer/add_unlocked",
  CREATE_RAZORPAY_ORDER: BASE_URL + "razorpay/create_order",
  GET_UNLOCKED_USERS: BASE_URL + "customer/get_unlocked/",
  CUSTOMER_PASSWORD_CHANGE: BASE_URL + "customer/change_password",
  SP_PASSWORD_CHANGE: BASE_URL + "serviceProvider/change_password",
  UPDATE_CUSTOMER_PROFILE: BASE_URL + "customer/update/",
  UPDATE_SP_PROFILE: BASE_URL + "serviceProvider/update/",
  GET_FAV_LEGALIST: BASE_URL + "customer/get_fav_legalist/",
  ADD_FAV_LEGALIST: BASE_URL + "customer/add_to_fav",
  REMOVE_FAV_LEGALIST: BASE_URL + "customer/remove_from_fav",
  SELECTED_IN_JOB: BASE_URL + "jobs/selected",
  JOB_CONFIRMATION: BASE_URL + "jobs/job_confirmation",
  ADD_RATING: BASE_URL + "serviceProvider/add_rating",
  ELIGIBLE_RATING_USERS: BASE_URL + "customer/rating_Users/",
  GETDETAILSMULTIPLE: BASE_URL + "serviceProvider/getDetailsSP",
  REPORTUSER: BASE_URL + "common/reportUser",
  GET_ALL_REPORTED_USERS: BASE_URL + "common/getAllReportedUsers",
  GET_ALL_REPORTS_OF_USER: BASE_URL + "common/getReportsForUser/",
  BLOCK: BASE_URL + "common/block",
  UNBLOCK: BASE_URL + "common/unblock",
  VIDEO_UPLOAD: BASE_URL + "video/upload",
  ALL_VIDEO: BASE_URL + "video",
  DELETE_VIDEO: BASE_URL + "video/",
};
